version: '3'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - POSTGRES_DB=DB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=123123
    restart: always

  helm-bot:
    environment:
      - SQL_HOST=database
      - SQL_PORT=5432
      - SQL_USER=USER
      - SQL_DATABASE=DB
      - SQL_PASSWORD=123123
      - TOKEN=YOURTOKEN
      - RCON_IP=RCONIP
      - RCON_PASSWORD=123123123
      - REG_CHANNEL_ID=123123123
      - PLAYERS_ROLE_ID=123123123
      - GUILD_ADM_ROLE_ID=123123123
    image: saddydead1/mchelmbot
    depends_on:
      - database
    restart: unless-stopped
    working_dir: /app

volumes:
  database_data: