name: docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t mchelmbot .

    - name: Login Docker Hub
      run: docker login -u ${{ secrets.LOGINDOCKERHUB }} -p ${{ secrets.DOCKERTOKEN }}

    - name: Push image
      run: docker push mchelmbot